spring:
  profiles:
    active: native
---    
spring:
  profiles: native
  cloud:
    config:
      server:
        native:
          search-locations:
            file://Users/Guest/downloads/ms-config-properties/{application}/{profile},
            file://Users/Guest/downloads/ms-config-properties/global/{profile}